"""
Generates bibleData.js.
This file should look like:

const bibleData = {
    Genesis: {
        chapters: {
            1: 5,
            2: 7,
            3: 10
        }
    },
    Exodus: {
        chapters: {
            1: 5,
            2: 7,
            3: 10
        }
    }
};

export default bibleData;
"""

import json

from bible_guesser.bible import Bible

bible = Bible()
bible_stripped_dict = {
    book: {"chapters": {chapter: bible[book][chapter].num_verses for chapter in bible[book].chapters}}
    for book in bible.books
}


with open("../bible-guesser-frontend/src/bibleData.js", "w") as file:
    file.write("// This file is generated by generate_bible_data.py.\n")
    file.write("const bibleData = ")
    json.dump(bible_stripped_dict, file, indent=4)
    file.write(";\n\nexport default bibleData;")
