repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: bash -c 'cd backend && poetry run black --config pyproject.toml .'
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: bash -c 'cd backend && poetry run isort --settings-file pyproject.toml .'
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: bash -c 'cd backend && poetry run mypy --config-file pyproject.toml .'
        language: system
        types: [python]
